### ISSUE TITLE
Rychle pridavani Adresnich bodu

### ISSUE THREAD

**Issue by pschonmann** [mkyral/josm-pointInfo#1]
Ahoj,
slo by udelat to ze kdyz budu drzet CTRL, nebo jiny modifier tak se mi automaticky prida nejblizsi adresni bod ? ( v menu tuto funkci zastava symbol zavinace )

**Comment by mkyral** [comment]
Do PointInfa bych to nedával, ale mohl by to být další modul pro Tracer.
