### ISSUE TITLE
Documentation translation

### ISSUE THREAD

**Issue by javiersanp** [mkyral/josm-pointInfo#4]
Hello.
I'm looking to traslate to spanish the plugin documentation an accommodate the Castastro functionality there. I think that a good method would be to add the plugin to this [wiki page](https://wiki.openstreetmap.org/wiki/JOSM/Plugins) and create a page for it. The English version would contain a short description and a link to the GitHub readme. The Spanish version would contain the translation of the readme and a description of the setup for Spanish users. I will be glad to do the job if you agree.
Cheers, Javier

**Comment by mkyral** [comment]
Hi,
Documentation is on my TODO list, so if you want, go ahead ;-)

**Comment by javiersanp** [comment]
Done.
https://wiki.openstreetmap.org/wiki/JOSM/Plugins/pointinfo
